sudo: required
services:
   - docker

before_install:
   - gem update --system
   - gem install bundler
   - docker build -t foundry/docker-react -f Dockerfile.dev .

script:
   - docker run foundry/docker-react npm run test -- --coverage
